hasher-useradd.in: Sync with hasher

diff --git a/hasher-priv/hasher-useradd.in b/hasher-priv/hasher-useradd.in
--- a/hasher-priv/hasher-useradd.in
+++ b/hasher-priv/hasher-useradd.in
@@ -1,6 +1,6 @@
 #!/bin/sh -e
 #
-# Copyright (C) 2003-2006  Dmitry V. Levin <ldv@altlinux.org>
+# Copyright (C) 2003-2007  Dmitry V. Levin <ldv@altlinux.org>
 # 
 # The useradd wrapper for the hasher-priv project
 #
@@ -21,15 +21,26 @@
 
 PROG="${0##*/}"
 
+Info()
+{
+	printf >&2 '%s\n' "${0##*/}: $*"
+}
+
 Fatal()
 {
-	echo "${0##*/}: $*" >&2
+	Info "$*"
 	exit 1
 }
 
-Usage()
+show_usage()
 {
-	[ "$1" = 0 ] || exec >&2
+	[ -z "$*" ] || Info "$*"
+	echo >&2 "Try \`$PROG --help' for more information."
+	exit 1
+}
+
+show_help()
+{
 	cat <<EOF
 hasher-useradd - adds hasher satellite users for already existing user,
 and creates hasher-priv config file.
@@ -44,7 +55,7 @@ Valid options are:
 
 By default, satellite user names will be choosen based on <user>.
 EOF
-	[ -n "$1" ] && exit "$1" || exit
+	exit
 }
 
 print_version()
@@ -53,14 +64,23 @@ print_version()
 hasher-useradd version @VERSION@
 Written by Dmitry V. Levin <ldv@altlinux.org>
 
-Copyright (C) 2003-2006  Dmitry V. Levin <ldv@altlinux.org>
+Copyright (C) 2003-2007  Dmitry V. Levin <ldv@altlinux.org>
 This is free software; see the source for copying conditions.  There is NO
 warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 EOF
 	exit
 }
 
-TEMP=`getopt -n $PROG -o h,V -l names:,number:,help,version -- "$@"` || Usage
+opt_check_number()
+{
+	[ -n "${2##0*}" -a -n "${2##*[!0-9]*}" ] &&
+		[ "$2" -ge 1 ] 2>/dev/null ||
+		Fatal "$1: $2: invalid number."
+	printf %s "$2"
+}
+
+TEMP=`getopt -n $PROG -o h,V -l names:,number:,help,version -- "$@"` ||
+	show_usage
 eval set -- "$TEMP"
 
 names=
@@ -69,30 +89,28 @@ while :; do
 	case "$1" in
 		--names) shift; names="$1"
 			;;
-		--number) shift; number="$1"
+		--number)
+			number="$(opt_check_number "$1" "$2")"
+			shift
 			;;
-		-h|--help) Usage 0
+		-h|--help) show_help
 			;;
 		-V|--version) print_version
 			;;
 		--) shift; break
 			;;
-		*) Fatal "unrecognized option: $1" >&2; exit 1
+		*) Fatal "unrecognized option: $1"; exit 1
 			;;
 	esac
 	shift
 done
 
-[ "$#" -eq 1 ] || Usage
+# Exactly one argument.
+[ "$#" -ge 1 ] || show_usage 'Insufficient arguments.'
+[ "$#" -le 1 ] || show_usage 'Too many arguments.'
 
 caller="$1"
 shift
-
-if [ -n "$number" ]; then
-	if ! [ "$number" -ge 1 ] 2>/dev/null; then
-		Fatal "invalid subconfig identifier: $number"
-	fi
-fi
 
 if [ -n "$names" ]; then
 	user1="${names%%:*}"
